image: python:3.9

stages:
  - test
  - document

before_script:
  - python -V  # Print out python version for debugging
  - pip install -r requirements.txt  # Install dependencies

test:
  stage: test
  script:
    - cd tests
    - python -m unittest discover -s .

document:
  stage: document
  script:
    - pip install sphinx  # Install Sphinx
    - cd docs
    - sphinx-apidoc -o . ../src  # Generate documentation from source code
    - make html  # Build HTML documentation
  artifacts:
    paths:
      - docs/_build/html
  only:
    - main
