image: python:3.9

stages:
  - test
  - document

before_script:
  - apt-get update && apt-get autoclean
  - apt-get install -y '^libxcb.*-dev' libx11-xcb-dev libglu1-mesa-dev libxrender-dev libxi-dev libxkbcommon-dev libxkbcommon-x11-dev libegl1-mesa libdbus-1-3 xvfb
  - python -m venv venv
  - source venv/bin/activate
  - pip install -r requirements.txt
  - pip install numpy
  - pip install opencv-python
  - pip install pytest pytest-qt # Install pytest and the QT plugin for pytest

test:
  stage: test
  script:
    - xvfb-run --auto-servernum --server-args="-screen 0 1024x768x24" pytest tests/ # Use xvfb-run to execute tests

document:
  stage: document
  script:
    - pip install sphinx  # Install Sphinx
    - cd docs
    - sphinx-apidoc -o . ../src  # Generate documentation from source code
    - make html  # Build HTML documentation
  artifacts:
    paths:
      - docs/_build/html
  only:
    - main
